name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  checks:
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # pseudo-matrix for convenience, NEVER use more than a single combination
        node: [22]
        os: [ubuntu-latest]
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            release-assets.githubusercontent.com:443
            registry.npmjs.org:443
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: 'false'
      - uses: ./.github/actions/setup-node
        with:
          node-version: ${{matrix.node}}
      - name: format
        run: pnpm check:format
      - name: lint
        if: ${{ !cancelled() }}
        run: pnpm check:lint
      - name: types
        if: ${{ !cancelled() }}
        run: pnpm check:types
      - name: publint
        if: ${{ !cancelled() }}
        run: pnpm check:publint
      - name: generated files are up to date
        if: ${{ !cancelled() }}
        run: pnpm generate && [ "`git status --porcelain=v1`" == "" ]

  # this is the test matrix, it runs with node18 and 20
  test:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [22]
        os: [ubuntu-latest, macos-latest, windows-latest]
        ts: ['current']
        include:
          - node: 18
            os: ubuntu-latest
            ts: 'current'
          - node: 20
            os: ubuntu-latest
            ts: 'current'
          - node: 24
            os: ubuntu-latest
            ts: 'current'
          - node: 22
            os: ubuntu-latest
            ts: 'beta'
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            release-assets.githubusercontent.com:443
            registry.npmjs.org:443
            cdn.playwright.dev:443
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: 'false'
      - id: disable_engine_strict
        name: disable engine strict
        if: matrix.node < 20
        run: echo "engine-strict=false" >> .npmrc
      - uses: ./.github/actions/setup-node
        with:
          node-version: ${{matrix.node}}
      - id: install_ts_beta
        name: install ts beta
        if: matrix.ts == 'beta'
        run: pnpm --dir packages/tsconfck install -D typescript@beta
      - name: run tests
        run: pnpm test
